Organizations:
  - &OrdererOrg
    Name: OrdererMSP
    ID: OrdererMSP
    MSPDir: ./crypto-config/ordererOrganizations/orderer.sedob.gov/orderers/orderer0.orderer.sedob.gov/msp
    Policies:
      Readers:
        Type: Signature
        Rule: "OR('OrdererMSP.member')"
      Writers:
        Type: Signature
        Rule: "OR('OrdererMSP.member')"
      Admins:
        Type: Signature
        Rule: "OR('OrdererMSP.admin')"
    OrdererEndpoints:
          - orderer.example.com:7050
  - &Org1
    Name: Org1MSP
    ID: Org1MSP
    MSPDir: ./crypto-config/peerOrganizations/org1.sedob.gov/peers/peer0.org1.sedob.gov/msp
    Policies:
      Readers:
        Type: Signature
        Rule: "OR('Org1MSP.admin', 'Org1MSP.peer', 'Org1MSP.client')"
      Writers:
        Type: Signature
        Rule: "OR('Org1MSP.admin', 'Org1MSP.client')"
      Admins:
        Type: Signature
        Rule: "OR('Org1MSP.admin')"
      Endorsement:
        Type: Signature
        Rule: "OR('Org1MSP.peer')"
    AnchorPeers:
      - Host: peer0.org1.sedob.gov
        Port: 7051


  - &Org2
    Name: Org2MSP
    ID: Org2MSP
    MSPDir: ./crypto-config/peerOrganizations/org2.sedob.gov/peers/peer0.org2.sedob.gov/msp
    Policies:
      Readers:
        Type: Signature
        Rule: "OR('Org2MSP.admin', 'Org2MSP.peer', 'Org2MSP.client')"
      Writers:
        Type: Signature
        Rule: "OR('Org2MSP.admin', 'Org2MSP.client')"
      Admins:
        Type: Signature
        Rule: "OR('Org2MSP.admin')"
    AnchorPeers:
    - Host: peer0.org2.sedob.gov
      Port: 7052


Capabilities:
  Channel: &ChannelCapabilities
    V2_0: true
  Orderer: &OrdererCapabilities
    V2_0: true
  Application: &ApplicationCapabilities
    V2_5: true

Application: &ApplicationDefaults
  ACLs: &ACLsDefault
    event/Block: /Channel/Application/Readers
    event/FilteredBlock: /Channel/Application/Readers
    chaincode/ChaincodeDeployment: /Channel/Application/Readers
    chaincode/ChaincodeUpgrade: /Channel/Application/Readers
    chaincode/GetMetadata: /Channel/Application/Readers
    chaincode/GetMetadataLSCC: /Channel/Application/Readers
    chaincode/GetInstantiatedChaincodes: /Channel/Application/Readers
    chaincode/GetInstantiatedChaincodesLSCC: /Channel/Application/Readers
    chaincode/GetCollectionsConfig: /Channel/Application/Readers
    chaincode/GetCollectionsConfigLSCC: /Channel/Application/Readers
    chaincode/GetChaincodeDefinition: /Channel/Application/Readers
    chaincode/GetChaincodeDefinitionLSCC: /Channel/Application/Readers
    chaincode/CheckCommitReadiness: /Channel/Application/Readers
    chaincode/CheckCommitReadinessLSCC: /Channel/Application/Readers
    chaincode/ApproveChaincodeDefinitionForMyOrg: /Channel/Application/Readers
    chaincode/ApproveChaincodeDefinitionForMyOrgLSCC: /Channel/Application/Readers
    chaincode/CommitChaincodeDefinition: /Channel/Application/Readers
    chaincode/CommitChaincodeDefinitionLSCC: /Channel/Application/Readers
  Organizations: 
  Policies:
    Readers:
      Type: ImplicitMeta
      Rule: "ANY Readers"
    Writers:
      Type: ImplicitMeta
      Rule: "ANY Writers"
    Admins:
      Type: ImplicitMeta
      Rule: "MAJORITY Admins"
    LifecycleEndorsement:
      Type: ImplicitMeta
      Rule: "MAJORITY Endorsement"
  Capabilities:
      <<: *ApplicationCapabilities

Orderer: &OrdererDefaults
  OrdererType: etcdraft
  Addresses:
    - orderer0.orderer.sedob.gov:7050

  BatchTimeout: 2s
  BatchSize:
    MaxMessageCount: 10
    AbsoluteMaxBytes: 99 MB
    PreferredMaxBytes: 512 KB
  Organizations: *OrdererOrg
  Policies:
    Readers:
      Type: ImplicitMeta
      Rule: "ANY Readers"
    Writers:
      Type: ImplicitMeta
      Rule: "ANY Writers"
    Admins:
      Type: ImplicitMeta
      Rule: "MAJORITY Admins"
    BlockValidation:
      Type: ImplicitMeta
      Rule: "ANY Writers"
  Capabilities:
    <<: *OrdererCapabilities
  EtcdRaft:
    Consenters:
      - Host: orderer0.orderer.sedob.gov
        Port: 7050
        ClientTLSCert: ./crypto-config/ordererOrganizations/orderer.sedob.gov/orderers/orderer0.orderer.sedob.gov/tls/server.crt
        ServerTLSCert: ./crypto-config/ordererOrganizations/orderer.sedob.gov/orderers/orderer0.orderer.sedob.gov/tls/server.crt


Channel: &ChannelDefaults
  Policies:
    Readers:
      Type: Signature
      Rule: "OR('Org1MSP.member', 'Org2MSP.member')"
    Writers:
      Type: Signature
      Rule: "OR('Org1MSP.member', 'Org2MSP.member')"
    Admins:
      Type: Signature
      Rule: "OR('Org1MSP.admin', 'Org2MSP.admin')"
  Capabilities:
    <<: *ChannelCapabilities

  Consortiums: 
    MyConsortium:
      Organizations:
        - *Org1
        - *Org2


Profiles:
  Test:
    Consortium: MyConsortium
    <<: *ChannelDefaults
    Application:
      <<: *ApplicationDefaults
      Organizations:
        - *Org1
        - *Org2
        - *OrdererOrg
      Capabilities:
        <<: *ApplicationCapabilities

  OrdererGenesis:
    <<: *ChannelDefaults
    Orderer:
      <<: *OrdererDefaults
      Organizations:
        - *OrdererOrg
    Consortiums:
      MyConsortium:
        Organizations:
          - *Org1
          - *Org2
