OrdererOrgs:
  - Name: OrdererMSP
    Domain: orderer.sedob.gov
    EnableNodeOUs: true
    Specs:
      - Hostname: orderer0
        CommonName: orderer0.orderer.sedob.gov

PeerOrgs:
  - Name: Org1MSP
    Domain: org1.sedob.gov
    EnableNodeOUs: true
    Template:
      Count: 1
    Users:
      Count: 1

  - Name: Org2MSP
    Domain: org2.sedob.gov
    EnableNodeOUs: true
    Template:
      Count: 1
    Users:
      Count: 1
